### ISSUE TITLE
Add Auto Update?

### ISSUE THREAD

**Issue by KorbsStudio** [Rabbit-Company/Passky-Desktop#6]
**Describe the solution you'd like**
Application will auto update if update is available.

Electron builder has a configuration you can add to get auto updating added pretty easily. I recommend self-hosting the update server rather than use GitHub Release, to avoid conflicts in the future with tokens.

**Comment by zigazajc007** [comment]
Hello,

Thanks for the suggestion.
Currently, I'm looking for a more lightweight Electron alternative.

NeutralinoJS and Tauri both look more promising.
Auto-Update would be added, but probably not in the next update as Electron would be replaced.

**Comment by KorbsStudio** [comment]
Supposedly, there is suppose to be something called "Electrino" which does put your Electron app on a diet. Although, I can't test it for you since it doesn't support Linux.

**Comment by zigazajc007** [comment]
NeutralinoJS does something similar to Electrino, but it also supports all platforms, so NeutralinoJS should be as of now better option.

Tauri has currently one "problem" that prevents fetching data from other servers. Their developer said that this would be fixed in the next update.

So when the next update of Passky Client will be really, I would test it on all frameworks, and decide which one works the best.
